name: CI
on:
 push:
   branches: [ develop ]
jobs:
 conviso-ast:
   runs-on: ubuntu-latest
   container:
     image: convisoappsec/convisocli:beta
     env:
       CONVISO_API_KEY: ${{secrets.CONVISO_API_KEY}}
       CONVISO_COMPANY_ID: 652
   steps:
   - uses: actions/checkout@v4
   - name: Run SCA
     run: |
          conviso sca run --vulnerability-auto-close