name: CI
on:
 push:
   branches: [ develop ]
 pull_request:
   branches: [develop, example]
jobs:
 chamar-conviso-ast:
   uses: gabrielvmayer/central-workflow/.github/workflows/main.yml@main
   with:
      CONVISO_ASSET_NAME: 'Goatlin'
   secrets:
      CONVISO_API_KEY: ${{ secrets.CONVISO_API_KEY }}
